name: Keep Backend Server Active

on:
  schedule:
    - cron: '*/10 * * * *' # co 10 minut
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Test backend endpoints
        run: |
          echo "Testing backend endpoints to keep server active..."
          
          # Test basic connectivity
          echo "Testing basic connectivity..."
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" https://qitchen-backend-5kql.onrender.com/api/reservations
          
          # Test auth endpoint (without credentials)
          echo "Testing auth endpoint..."
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" -X POST https://qitchen-backend-5kql.onrender.com/api/auth/login
          
          # Test table types endpoint
          echo "Testing table types endpoint..."
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" https://qitchen-backend-5kql.onrender.com/api/table-types
          
          # Test restaurant endpoint
          echo "Testing restaurant endpoint..."
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" https://qitchen-backend-5kql.onrender.com/api/restaurant
          
          echo "Backend server kept active successfully!"
          
      - name: Simulate user activity
        run: |
          echo "Simulating user activity..."
          
          # Make multiple requests to simulate real usage
          for i in {1..3}; do
            echo "Request $i:"
            curl -s -o /dev/null -w "HTTP Status: %{http_code}, Response Time: %{time_total}s\n" https://qitchen-backend-5kql.onrender.com/api/reservations
            sleep 2
          done
          
          echo "User activity simulation completed!" 